### ISSUE TITLE
Rendering problems

### ISSUE THREAD

**Issue by Apromixately** [trogdoro/dotsies#3]
When trying to use dotsies in a webpage  I get rendering problems.
The same happens when pasting custom text in the story reader.
(tested in Firefox and IE)
Note all the excess dots on top in the screenshot below.

![image](https://user-images.githubusercontent.com/19586851/51258254-d7129f00-19a9-11e9-8833-869a65d05a79.png)

**Comment by refola** [comment]
The screenshot looks fine to me. That said, the tutorial fails to mention that smaller dots over letters are used for capitalization. Perhaps this is what you're seeing?

Example: The top line in this image is `abcdefghijklmnopqrstuvwxyz` and the bottom line is `ABCDEFGHIJKLMNOPQRSTUVWXYZ`.
![Screenshot_20190417_090703](https://user-images.githubusercontent.com/8690113/56303435-c54baf80-60f0-11e9-98df-6a32620ec9bb.png)

**Comment by Apromixately** [comment]
Yup, thanks. :)
